server:
  port: 8088

spring:
  thymeleaf:   ###THYMELEAF (ThymeleafAutoConfiguration)
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  #freemarker:
    #cache: false
    #charset: UTF-8
    #check-template-location: true
    #content-type: text/html
    #expose-request-attributes: true
    #xpose-session-attributes: true
    #request-context-attribute: request
  http:               ### FILEUPLOAD
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

#自定义属性，文件上传路径
fileupload:
  path: E:test/

