server:
  port: 8082
spring:
  application:
    name: service2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
