# 服务器端口号    
server:
  port: 7902
# 是否生成ddl语句    
spring:
  jpa:
    generate-ddl: false
# 是否打印sql语句    
    show-sql: true
# 自动生成ddl，由于指定了具体的ddl，此处设置为none    
    hibernate:
      ddl-auto: none
# 使用H2数据库    
  datasource:
    platform: h2
# 指定生成数据库的schema文件位置    
    schema: classpath:schema.sql
# 指定插入数据库语句的脚本位置    
    data: classpath:data.sql
